/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CSTEpisodicMemory;

import WS3DCoppelia.util.Constants;
import br.unicamp.cst.util.viewer.MindViewer;

import java.util.logging.Level;
import java.util.logging.Logger;

public class ExperimentMain {

    public static void main(String[] args) {
        Logger.getLogger("codelets").setLevel(Level.SEVERE);
        // Create Environment
        Environment env=new Environment(); //Creates only a creature and some apples
        AgentMind a = new AgentMind(env);  // Creates the Agent Mind and start it
        // The following lines create the MindViewer and configure it
        MindViewer mv = new MindViewer(a,"MindViewer", a.bList);
        mv.setVisible(true);
        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() {
                env.stopSimulation();
            }
        });
        runTestCommands(env);
    }

    public static void runTestCommands(Environment env){
        env.world.createThing(Constants.JewelTypes.RED_JEWEL, 0.2f, 9.5f);
        env.world.createThing(Constants.JewelTypes.BLUE_JEWEL, 0.4f, 9.5f);
        env.world.createThing(Constants.JewelTypes.GREEN_JEWEL, 0.6f, 9.5f);
        env.world.createThing(Constants.JewelTypes.WHITE_JEWEL, 0.8f, 9.5f);
        env.world.createThing(Constants.JewelTypes.MAGENTA_JEWEL, 1.0f, 9.5f);
        env.world.createThing(Constants.JewelTypes.YELLOW_JEWEL, 1.2f, 9.5f);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ExperimentMain.class.getName()).log(Level.SEVERE, null, ex);
        }
//        env.creature.moveTo(2f,2f);
//        try {
//            Thread.sleep(5000);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(ExperimentMain.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        env.creature.moveTo(3f,1f);
//        try {
//            Thread.sleep(5000);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(ExperimentMain.class.getName()).log(Level.SEVERE, null, ex);
//        }
        env.creature.moveTo(0.5f,2f);
        try {
            Thread.sleep(7000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ExperimentMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        env.creature.moveTo(0.5f,9f);
    }
}
