/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CSTEpisodicMemory;

import org.junit.jupiter.api.Test;
import static org.junit.Assert.*;

public class EnvironmentTest {

    @Test
    public void environmentInitializedTest() {
        Environment env = new Environment();
        assertNotNull(env.creature);
        assertNotNull(env.world);
        assertTrue(env.initialized);

        env.stopSimulation();
        assertFalse(env.initialized);
    }
}
